# Generated by Django 3.2.11 on 2022-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('batch_id', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='Phsensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorName', models.CharField(blank=True, max_length=8)),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'ph',
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorName', models.CharField(blank=True, max_length=10)),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'temperature',
            },
        ),
    ]
