# Generated by Django 4.0.1 on 2022-01-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0002_rename_ph_phsensor_rename_tm_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phsensor',
            name='sensorName',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='temp',
            name='sensorName',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
