# Generated by Django 4.0.1 on 2022-01-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0003_phsensor_sensorname_temp_sensorname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='batch',
            table='batch',
        ),
    ]
