# Generated by Django 4.0.1 on 2022-01-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaapp', '0004_alter_batch_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phsensor',
            table='ph',
        ),
        migrations.AlterModelTable(
            name='temp',
            table='temperature',
        ),
    ]
